# fly.toml app configuration file generated for horoconsultant-core-backend on 2026-08-08T12:30:44+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'horoconsultant-core-backend'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile.hf'

[env]
  ADMIN_ALLOWED_EMAILS = 'pansakorn@gmail.com,kimlenglim.work@gmail.com'
  PORT = '7860'

[[services]]
  protocol = 'tcp'
  internal_port = 7860
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.http_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'
    method = 'get'
    path = '/health'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
