{
 "title": "Alert Groups Insights",
 "tags": [
  "oncall",
  "irm",
  "alert groups"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "alert_groups_total", "label": "alert_groups_total", "query": { "query": "metrics(.*alert_groups_total)" } },
   {
    "name": "alert_groups_response_time_seconds_count",
    "label": "alert_groups_response_time_seconds_count",
    "query": {
     "query": "metrics(.*alert_groups_response_time_seconds_count)"
    }
   },
   {
    "name": "alert_groups_response_time_seconds_sum",
    "label": "alert_groups_response_time_seconds_sum",
    "query": {
     "query": "metrics(.*alert_groups_response_time_seconds_sum)"
    }
   },
   {
    "name": "alert_groups_response_time_seconds_bucket",
    "label": "alert_groups_response_time_seconds_bucket",
    "query": {
     "query": "metrics(.*alert_groups_response_time_seconds_bucket)"
    }
   },
   {
    "name": "user_was_notified_of_alert_groups_total",
    "label": "user_was_notified_of_alert_groups_total",
    "query": {
     "query": "metrics(.*user_was_notified_of_alert_groups_total)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(${alert_groups_total},slug)"
    }
   },
   {
    "name": "team",
    "label": "Team",
    "query": {
     "query": "label_values(${alert_groups_total}{slug=~\"$instance\"},team)"
    }
   },
   {
    "name": "integration",
    "label": "Integration",
    "query": {
     "query": "label_values(${alert_groups_total}{team=~\"$team\",slug=~\"$instance\"},integration)"
    }
   },
   {
    "name": "service_name",
    "label": "Service name",
    "query": {
     "query": "label_values(${alert_groups_total}{slug=~\"$instance\", team=~\"$team\"},service_name)"
    }
   },
   {
    "name": "alert_groups_resolution_time_seconds_count",
    "label": "alert_groups_resolution_time_seconds_count",
    "query": "metrics(.*alert_groups_resolution_time_seconds_count)"
   },
   {
    "name": "alert_groups_resolution_time_seconds_sum",
    "label": "alert_groups_resolution_time_seconds_sum",
    "query": "metrics(.*alert_groups_resolution_time_seconds_sum)"
   },
   {
    "name": "alert_groups_resolution_time_seconds_bucket",
    "label": "alert_groups_resolution_time_seconds_bucket",
    "query": "metrics(.*alert_groups_resolution_time_seconds_bucket)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 0 },
   "options": {
    "content": "<div>\n  <img src=\"/public/plugins/grafana-irm-app/img/logo.svg\">\n</div>"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 23, "x": 1, "y": 0 }, "options": { "content": "# Alert Groups Insights" } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
   "options": {
    "content": "📣 This is a read-only dashboard. To make a copy, click \"Settings\" and \"Save as\".\n\n📝 If you see *\"No data\"* errors, check the right datasource is selected\nand that you have already used and setup the [IRM](/a/grafana-irm-app/alert-groups) plugin.\nYou can also try [re-importing the dashboard](/plugins/grafana-irm-app?page=dashboards)\nto confirm you have the latest updates. If you just copied the dashboard,\nyou may need to reload it."
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "New alert groups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(delta(sum(alert_groups_total{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"})[$__range:])) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Mean time to respond (MTTR)",
   "type": "stat",
   "description": "Mean time between the start and first action of all alert groups for the last 7 days",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum(alert_groups_response_time_seconds_sum{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}) / sum(alert_groups_response_time_seconds_count{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}))[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New alert groups",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "round(delta(sum by (integration) (alert_groups_total{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"})[$__interval:])) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean time to respond (MTTR)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(sum(alert_groups_response_time_seconds_sum{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}) / sum(alert_groups_response_time_seconds_count{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Integrations data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Alert groups by Integration",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sort_desc(round(delta(sum by (integration)(alert_groups_total{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"})[$__range:])) >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean time to respond (MTTR) by Integration",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(avg_over_time((sum by (integration)(alert_groups_response_time_seconds_sum{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}) / sum by (integration)(alert_groups_response_time_seconds_count{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}))[$__range:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Teams data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Alert groups by Team",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sort_desc(round(delta(sum by (team)(alert_groups_total{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"})[$__range:])) >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean time to respond (MTTR) by Team",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(avg_over_time((sum by(team) (alert_groups_response_time_seconds_sum{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}) / sum by(team)(alert_groups_response_time_seconds_count{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}))[$__range:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notified alert groups by Users (based on all Teams and Integrations)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "New alert groups notifications",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "round(delta(sum by (username)(user_was_notified_of_alert_groups_total{slug=~\"$instance\"})[$__interval:])) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New alert groups notifications",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(round(delta(sum by (username)(user_was_notified_of_alert_groups_total{slug=~\"$instance\"})[$__range:])) >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Time to Resolve (MTTR) Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 }
  },
  {
   "title": "Average Mean time to resolve (MTTR)",
   "type": "stat",
   "description": "Mean time between the start and first action of all alert groups for the last 7 days",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum(alert_groups_resolution_time_seconds_sum{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}) / sum(alert_groups_resolution_time_seconds_count{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}))[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean time to resolve (MTTR)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(sum(alert_groups_resolution_time_seconds_sum{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}) / sum(alert_groups_resolution_time_seconds_count{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean time to resolve (MTTR) by Integration",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(avg_over_time((sum by (integration)(alert_groups_resolution_time_seconds_sum{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}) / sum by (integration)(alert_groups_resolution_time_seconds_count{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}))[$__range:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean time to resolve (MTTR) by Team",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(avg_over_time((sum by(team) (alert_groups_resolution_time_seconds_sum{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}) / sum by(team)(alert_groups_resolution_time_seconds_count{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\", service_name=~\"$service_name\"}))[$__range:]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}