#!/usr/bin/env python3
"""Generate native Codex subagent TOML files from legacy workspace agents.

The existing Antigravity synchronizer owns the legacy source tree. This tool
only reads `.agents/agents/*/agent.json` and produces the Codex compatibility
target in `.codex/agents/`.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE_DIR = ROOT / ".agents" / "agents"
DEFAULT_OUTPUT_DIR = ROOT / ".codex" / "agents"
GENERATED_HEADER = "# Generated by scripts/sync_codex_agents.py from "
REQUIRED_FIELDS = ("name", "description", "system_prompt")


class AgentDefinitionError(ValueError):
    """Raised when a legacy agent cannot become a valid Codex configuration."""


def relative_display(path: Path) -> str:
    """Return a stable project-relative path when possible."""
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def load_agents(source_dir: Path) -> dict[str, tuple[Path, dict[str, Any]]]:
    """Load and validate the legacy JSON definitions used by this compatibility layer."""
    if not source_dir.is_dir():
        raise AgentDefinitionError(f"Source agent directory does not exist: {source_dir}")

    agents: dict[str, tuple[Path, dict[str, Any]]] = {}
    source_files = sorted(source_dir.glob("*/agent.json"))
    if not source_files:
        raise AgentDefinitionError(f"No legacy agent definitions found in: {source_dir}")

    for source in source_files:
        try:
            data = json.loads(source.read_text(encoding="utf-8"))
        except json.JSONDecodeError as error:
            raise AgentDefinitionError(f"Malformed JSON in {relative_display(source)}: {error.msg}") from error

        if not isinstance(data, dict):
            raise AgentDefinitionError(f"Agent definition must be an object: {relative_display(source)}")

        for field in REQUIRED_FIELDS:
            value = data.get(field)
            if not isinstance(value, str) or not value.strip():
                raise AgentDefinitionError(
                    f"Missing non-empty '{field}' in {relative_display(source)}"
                )

        name = data["name"]
        if name in agents:
            raise AgentDefinitionError(f"Duplicate agent name '{name}' in {relative_display(source)}")
        agents[name] = (source, data)

    return agents


def normalized_legacy_skills(data: dict[str, Any]) -> list[str]:
    """Normalize legacy `.skill` suffixes for guidance without mutating source data."""
    tools = data.get("tools", [])
    if not isinstance(tools, list):
        return []

    skills: list[str] = []
    for tool in tools:
        if not isinstance(tool, str) or not tool.strip():
            continue
        skill = tool.removesuffix(".skill")
        if skill not in skills:
            skills.append(skill)
    return skills


def render_codex_agent(source: Path, data: dict[str, Any]) -> str:
    """Render one portable Codex subagent TOML configuration."""
    skills = normalized_legacy_skills(data)
    guidance = [
        "",
        "",
        "## Codex compatibility guidance",
        f"- Legacy source: `{relative_display(source)}`.",
        "- The legacy source remains authoritative; do not edit generated Codex TOML manually.",
        "- Model-allocation statements above are historical context only; inherit the active Codex model.",
    ]
    if skills:
        rendered_skills = ", ".join(f"`${skill}`" for skill in skills)
        guidance.append(
            f"- When the task matches their descriptions, use the relevant repository skills: {rendered_skills}."
        )

    instructions = data["system_prompt"].rstrip() + "\n" + "\n".join(guidance) + "\n"
    return "\n".join(
        (
            f"{GENERATED_HEADER}{relative_display(source)}. Do not edit manually.",
            f"name = {json.dumps(data['name'], ensure_ascii=False)}",
            f"description = {json.dumps(data['description'], ensure_ascii=False)}",
            f"developer_instructions = {json.dumps(instructions, ensure_ascii=False)}",
            "",
        )
    )


def expected_outputs(source_dir: Path) -> dict[str, str]:
    """Build deterministic filenames and contents for all legacy roles."""
    return {
        f"{name}.toml": render_codex_agent(source, data)
        for name, (source, data) in sorted(load_agents(source_dir).items())
    }


def check_outputs(output_dir: Path, expected: dict[str, str]) -> int:
    """Report missing, stale, or orphaned generated configs without writing files."""
    mismatches = 0
    for filename, content in expected.items():
        target = output_dir / filename
        if not target.exists():
            print(f"[ERROR] Missing Codex agent definition: {filename}")
            mismatches += 1
        elif target.read_text(encoding="utf-8") != content:
            print(f"[ERROR] Stale Codex agent definition: {filename}")
            mismatches += 1

    if output_dir.is_dir():
        for target in sorted(output_dir.glob("*.toml")):
            if target.name in expected:
                continue
            if target.read_text(encoding="utf-8").startswith(GENERATED_HEADER):
                print(f"[ERROR] Orphaned generated Codex agent definition: {target.name}")
                mismatches += 1

    if mismatches:
        print(f"[ERROR] Found {mismatches} Codex agent synchronization issue(s).")
        return 1

    print(f"[OK] All {len(expected)} Codex agent definitions are synchronized!")
    return 0


def write_outputs(output_dir: Path, expected: dict[str, str]) -> int:
    """Write expected TOML files and remove only obsolete files created by this tool."""
    output_dir.mkdir(parents=True, exist_ok=True)
    changed = 0
    for filename, content in expected.items():
        target = output_dir / filename
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            target.write_text(content, encoding="utf-8")
            changed += 1

    removed = 0
    for target in sorted(output_dir.glob("*.toml")):
        if target.name in expected:
            continue
        if target.read_text(encoding="utf-8").startswith(GENERATED_HEADER):
            target.unlink()
            removed += 1

    print(
        f"[OK] Generated {len(expected)} Codex agent definitions "
        f"({changed} updated, {removed} obsolete generated file(s) removed)."
    )
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse CLI options for normal generation and read-only validation."""
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--sync", action="store_true", help="Write generated Codex agent definitions.")
    mode.add_argument("--check", action="store_true", help="Check generated definitions without writing.")
    parser.add_argument(
        "--source-dir", type=Path, default=DEFAULT_SOURCE_DIR, help="Legacy agent definition directory."
    )
    parser.add_argument(
        "--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR, help="Codex TOML output directory."
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Run the Codex compatibility synchronizer."""
    args = parse_args(argv)
    try:
        expected = expected_outputs(args.source_dir)
    except AgentDefinitionError as error:
        print(f"[ERROR] {error}")
        return 1

    if args.check:
        return check_outputs(args.output_dir, expected)
    return write_outputs(args.output_dir, expected)


if __name__ == "__main__":
    sys.exit(main())
