[build-system]
requires = ["maturin==1.14.1"]
build-backend = "maturin"

[project]
name = "rust_core"
requires-python = ">=3.10"
dynamic = ["version"]

[tool.maturin]
bindings = "pyo3"
features = ["python-extension", "server"]
module-name = "rust_core._native"
python-source = ".."
exclude = [
    "rust_core/*.so",
    "rust_core/*.dylib",
    "rust_core/target",
    "rust_core/target/**",
    "rust_core/wheelhouse",
    "rust_core/wheelhouse/**",
    "target",
    "target/**",
    "wheelhouse",
    "wheelhouse/**",
]
